name: Verify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: corepack enable
      - run: corepack yarn install --immutable
      - run: corepack yarn playwright install --with-deps chromium
      - run: corepack yarn typecheck
      - run: corepack yarn test
      - run: corepack yarn build
